In [1]:
#Dependencies
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd 
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [2]:
#assigming index id to movie_name and rearranging df so that it's the first column
movie = pd.read_csv('Final_Data_Template.csv',encoding='latin-1')
movie['id'] = movie.index
movie = movie[['id'] + movie.columns[:-1].tolist()]
movie_final = movie.drop(['movie_name'], axis=1)
movie_final.head(3)

,id,production_year,production_budget,domestic_box_office,international_box_office,Success_Failure_All,Success_Failure_Domestic,rating,creative_type,source,...,350k_Movies.actor3_name,350k_Movies.actor3_gender,350k_Movies.actor4_name,350k_Movies.actor4_gender,350k_Movies.actor5_name,350k_Movies.actor5_gender,350k_Movies.director_name,350k_Movies.producer_name,350k_Movies.screeplay_name,350k_Movies.editor_name
0,0,2006,45000000,36895141,28700000,0,0,PG-13,Contemporary Fiction,Original Screenplay,...,David Morse,2,Jenna Stern,0,David Zayas,2,Richard Donner,Randall Emmett,Richard Wenk,Steve Mirkovich
1,1,2006,35000000,7459300,34604805,0,0,PG-13,Contemporary Fiction,Based on Fiction Book/Short Story,...,Albert Finney,0,Tom Hollander,2,Abbie Cornish,1,Ridley Scott,Ridley Scott,none,Dody Dorn
2,2,2006,10000000,20342852,6373339,1,1,PG-13,Contemporary Fiction,Original Screenplay,...,Virginia Madsen,1,Woody Harrelson,2,Garrison Keillor,2,Robert Altman,Robert Altman,Garrison Keillor,Jacob Craycroft

In [3]:
#Got dummies - 14169 columns...
movie_final = pd.get_dummies(movie_final)
movie_final.head(3)

,id,production_year,production_budget,domestic_box_office,international_box_office,Success_Failure_All,Success_Failure_Domestic,sequel,running_time,350k_Movies.popularity,...,350k_Movies.editor_name_William Steinkamp,350k_Movies.editor_name_William Yeh,350k_Movies.editor_name_Wyatt Jones,350k_Movies.editor_name_Wyatt Smith,350k_Movies.editor_name_Yann HervÃ©,350k_Movies.editor_name_Yves Langlois,350k_Movies.editor_name_Zach Staenberg,350k_Movies.editor_name_Zachary Stuart-Pontier,350k_Movies.editor_name_Zene Baker,350k_Movies.editor_name_none
0,0,2006,45000000,36895141,28700000,0,0,0,105,2.815345,...,0,0,0,0,0,0,0,0,0,0
1,1,2006,35000000,7459300,34604805,0,0,0,118,0.915594,...,0,0,0,0,0,0,0,0,0,0
2,2,2006,10000000,20342852,6373339,1,1,0,105,1.272709,...,0,0,0,0,0,0,0,0,0,0

In [28]:
#created dataframe with correlations for all columns 
name = []
correlation = []
for movie in movie_final:
    name.append(movie)
    correlation.append(movie_final['Success_Failure_Domestic'].corr(movie_final[movie]))
correlation_df = pd.DataFrame({'name': name, 'correlation': correlation})[['name','correlation']]
positive_df = correlation_df.sort_values(by=['correlation'], ascending=False)
positive_df.head(50)

                                                    name  correlation
6                               Success_Failure_Domestic     1.000000
5                                    Success_Failure_All     0.459041
3                                    domestic_box_office     0.318460
3946   350k_Movies.production_countries_United States...     0.150480
6979              350k_Movies.actor1_name_Sandra Bullock     0.130448
10                                   350k_Movies.revenue     0.130258
13                                350k_Movies.vote_count     0.128674
13976            350k_Movies.editor_name_Michael L. Sale     0.119041
12946           350k_Movies.producer_name_William Packer     0.119041
3703   350k_Movies.production_companies_Lions Gate Films     0.115623
12                              350k_Movies.vote_average     0.113771
12390   350k_Movies.producer_name_Christopher Meledandri     0.106436
7035                  350k_Movies.actor1_name_Tobin Bell     0.106436
7049                 350k_Movies.actor1_name_Tyler Perry     0.103342
12236              350k_Movies.director_name_Tyler Perry     0.103342
26                    creative_type_Contemporary Fiction     0.098204
4                               international_box_office     0.097208
37                  source_Based on Factual Book/Article     0.093442
7682            350k_Movies.actor2_name_Melissa McCarthy     0.092144
13522        350k_Movies.screeplay_name_Scott Neustadter     0.092144
12542                 350k_Movies.producer_name_Ice Cube     0.092144
7585                  350k_Movies.actor2_name_Kevin Hart     0.092144
7253             350k_Movies.actor2_name_Costas Mandylor     0.092144
13391       350k_Movies.screeplay_name_Melissa Rosenberg     0.092144
248    350k_Movies.genres_Adventure|Fantasy|Drama|Rom...     0.092144
7834            350k_Movies.actor2_name_Robert Pattinson     0.092144
12207                350k_Movies.director_name_Tim Story     0.089358
13951               350k_Movies.editor_name_Mark Livolsi     0.089358
71                                          genre_Horror     0.087679
12623              350k_Movies.producer_name_Judd Apatow     0.084542
67                                          genre_Comedy     0.081170
10174            350k_Movies.actor4_name_Woody Harrelson     0.080262
327                    350k_Movies.genres_Comedy|Romance     0.077818
9                                 350k_Movies.popularity     0.076618
6789             350k_Movies.actor1_name_Kristen Stewart     0.076236
6450              350k_Movies.actor1_name_Bradley Cooper     0.076236
7065              350k_Movies.actor1_name_Zachary Gordon     0.075209
8842              350k_Movies.actor3_name_Rachael Harris     0.075209
4812                      350k_Movies.release_date_39787     0.075209
11014              350k_Movies.actor5_name_Nick Offerman     0.075209
4585                 350k_Movies.release_date_28/09/2007     0.075209
10516               350k_Movies.actor5_name_Ellie Kemper     0.075209
9250                  350k_Movies.actor4_name_Cary Elwes     0.075209
4074                 350k_Movies.release_date_15/11/2013     0.075209
9115              350k_Movies.actor4_name_Allison Janney     0.075209
4416                 350k_Movies.release_date_24/07/2009     0.075209
13140            350k_Movies.screeplay_name_Drew Goddard     0.075209
7973                350k_Movies.actor2_name_Vera Farmiga     0.075209
8153              350k_Movies.actor3_name_Bradley Cooper     0.075209
12869       350k_Movies.producer_name_Sean S. Cunningham     0.075209

In [35]:
#making a list based off the top correlated columns to feed into regression
top = positive_df['name'].values.tolist()[:50]
top.remove('domestic_box_office')
top.remove('international_box_office')
top.remove('350k_Movies.revenue')
top.remove('Success_Failure_Domestic')
top.remove('Success_Failure_All')
# top.remove('id')

top[:50]

['350k_Movies.production_countries_United States of America',
 '350k_Movies.actor1_name_Sandra Bullock',
 '350k_Movies.vote_count',
 '350k_Movies.editor_name_Michael L. Sale',
 '350k_Movies.producer_name_William Packer',
 '350k_Movies.production_companies_Lions Gate Films',
 '350k_Movies.vote_average',
 '350k_Movies.producer_name_Christopher Meledandri',
 '350k_Movies.actor1_name_Tobin Bell',
 '350k_Movies.actor1_name_Tyler Perry',
 '350k_Movies.director_name_Tyler Perry',
 'creative_type_Contemporary Fiction',
 'source_Based on Factual Book/Article',
 '350k_Movies.actor2_name_Melissa McCarthy',
 '350k_Movies.screeplay_name_Scott Neustadter',
 '350k_Movies.producer_name_Ice Cube',
 '350k_Movies.actor2_name_Kevin Hart',
 '350k_Movies.actor2_name_Costas Mandylor',
 '350k_Movies.screeplay_name_Melissa Rosenberg',
 '350k_Movies.genres_Adventure|Fantasy|Drama|Romance',
 '350k_Movies.actor2_name_Robert Pattinson',
 '350k_Movies.director_name_Tim Story',
 '350k_Movies.editor_name_Mark Livolsi',
 'genre_Horror',
 '350k_Movies.producer_name_Judd Apatow',
 'genre_Comedy',
 '350k_Movies.actor4_name_Woody Harrelson',
 '350k_Movies.genres_Comedy|Romance',
 '350k_Movies.popularity',
 '350k_Movies.actor1_name_Kristen Stewart',
 '350k_Movies.actor1_name_Bradley Cooper',
 '350k_Movies.actor1_name_Zachary Gordon',
 '350k_Movies.actor3_name_Rachael Harris',
 '350k_Movies.release_date_39787',
 '350k_Movies.actor5_name_Nick Offerman',
 '350k_Movies.release_date_28/09/2007',
 '350k_Movies.actor5_name_Ellie Kemper',
 '350k_Movies.actor4_name_Cary Elwes',
 '350k_Movies.release_date_15/11/2013',
 '350k_Movies.actor4_name_Allison Janney',
 '350k_Movies.release_date_24/07/2009',
 '350k_Movies.screeplay_name_Drew Goddard',
 '350k_Movies.actor2_name_Vera Farmiga',
 '350k_Movies.actor3_name_Bradley Cooper',
 '350k_Movies.producer_name_Sean S. Cunningham']

In [42]:
#Replace top in next cell with x_names to run it with all features

# x_names = list(movie_final.columns.values)
# x_names.remove('domestic_box_office')
# x_names.remove('international_box_office')
# x_names.remove('id')
# x_names.remove('350k_Movies.revenue')
# x_names.remove('Success_Failure_Domestic')
# x_names.remove('Success_Failure_All')

In [48]:
#logistic regression copy/paste
X = movie_final[top]
y = movie_final["Success_Failure_Domestic"]

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [50]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [51]:
classifier.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [52]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.8364312267657993
Testing Data Score: 0.8189415041782729